---
title: "China Watchers"
output: html_notebook
---

```{r echo=FALSE, results = FALSE, include=FALSE}
if(!require(dplyr)) install.packages("dplyr", repos = "http://cran.us.r-project.org")
if(!require(geojsonio)) install.packages("geojsonio", repos = "http://cran.us.r-project.org")
if(!require(leaflet)) install.packages("leaflet", repos = "http://cran.us.r-project.org")
if(!require(RColorBrewer)) install.packages("RColorBrewer", repos = "http://cran.us.r-project.org")

library(dplyr)
library(geojsonio)
library(leaflet)
library(RColorBrewer)
```
```{r Importing dataset, include=FALSE}
# Preparing dataset
df_china_invest = read.csv('./input_data/china_investments.csv')
countries = read.csv("./input_data/countries_codes_and_coordinates.csv")
worldcountry = geojson_read("./input_data/50m.geojson", what = "sp")
```
```{r Preparing dataset, include=FALSE}
# check consistency of country names across datasets
df_china_invest = df_china_invest %>%
  filter(Country != 'South Sudan') %>% 
  mutate(Country = gsub("Britain", "UK", Country)) %>%
  mutate(Country = gsub("Laos", "Lao People's Democratic Republic", Country)) %>%
  mutate(Country = gsub("Iran", "Iran (Islamic Republic of)", Country)) %>%
  mutate(Country = gsub("UAE", "United Arab Emirates", Country)) %>%
  mutate(Country = gsub("\\<Congo\\>", "Democratic Republic of the Congo", Country)) %>% 
  mutate(Country = gsub("Tanzania", "Tanzania, United Republic of", Country)) %>%
  mutate(Country = gsub("Trinidad-Tobago", "Trinidad & Tobago", Country)) %>%
  mutate(Country = gsub("Bahamas", "The Bahamas", Country)) %>%
  mutate(Country = gsub("South Korea", "Republic of Korea", Country)) %>%
  mutate(Country = gsub("Bosnia", "Bosnia and Herzegovina", Country)) %>%
  mutate(Country = gsub("North Korea", "Korea, Democratic People's Republic of", Country)) %>%
  mutate(Country = gsub("Sao Tome", "Sao Tome and Principe", Country)) %>%
  mutate(Country = gsub("Macedonia", "North Macedonia", Country)) %>%
  mutate(Country = gsub("Moldova", "Moldova, Republic of", Country))

if (all(unique(df_china_invest$Country) %in% unique(countries$country))==FALSE) { print("Error: inconsistent country names")}

df_china_invest = merge(df_china_invest, countries, by.x = "Country", by.y = "country")
df_china_invest$Quantity.in.Millions = as.numeric(gsub("\\$", "", df_china_invest$Quantity.in.Millions))
df_china_invest_grouped = df_china_invest %>%
  filter(!is.na(Quantity.in.Millions)) %>%
  group_by(Country, Sector) %>%
  summarise(Investment_Count=n(),
            amount=sum(Quantity.in.Millions),
            alpha3, numeric, latitude, longitude) %>%
  distinct(Country, Sector, .keep_all = TRUE)

df_china_invest_grouped_all = df_china_invest_grouped %>%
  group_by(Country) %>%
  summarise(amount=sum(amount),
            alpha3, numeric, latitude, longitude) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_agri = df_china_invest_grouped %>%
  filter(Sector=='Agriculture') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_energy = df_china_invest_grouped %>%
  filter(Sector=='Energy') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_trans = df_china_invest_grouped %>%
  filter(Sector=='Transport') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_chem = df_china_invest_grouped %>%
  filter(Sector=='Chemicals') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_metals = df_china_invest_grouped %>%
  filter(Sector=='Metals') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_util = df_china_invest_grouped %>%
  filter(Sector=='Utilities') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_real = df_china_invest_grouped %>%
  filter(Sector=='Real estate') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_fin = df_china_invest_grouped %>%
  filter(Sector=='Finance') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_tech = df_china_invest_grouped %>%
  filter(Sector=='Technology') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_other = df_china_invest_grouped %>%
  filter(Sector=='Other') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_ent = df_china_invest_grouped %>%
  filter(Sector=='Entertainment') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_logs = df_china_invest_grouped %>%
  filter(Sector=='Logistics') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_fin = df_china_invest_grouped %>%
  filter(Sector=='Finance') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_tour = df_china_invest_grouped %>%
  filter(Sector=='Tourism') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)

df_china_invest_grouped_health = df_china_invest_grouped %>%
  filter(Sector=='Health') %>%
  group_by(Country) %>%
  distinct(Country, .keep_all = TRUE) %>%
  arrange(alpha3)
```
```{r Building basemap, include=FALSE}
plot_map <- worldcountry[worldcountry$ADM0_A3 %in% unique(df_china_invest_grouped$alpha3), ]
basemap = leaflet(plot_map, options = leafletOptions(minZoom = 1.25, 
                                                      worldCopyJump=FALSE,
                                                      maxBounds = list(
                                                        list(-90, -180),
                                                        list(90, 180)))) %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>%
  addLayersControl(
    position='bottomleft',
    baseGroups=c("All", "Agriculture", "Energy", "Transport", "Chemicals", "Metals", "Utilities", "Real estate", "Finance", "Technology", "Other", "Entertainment", "Logistics", "Tourism", "Health"),
    options = layersControlOptions(collapsed = FALSE)) %>% 
  clearBounds()
```
```{r}
# create plotting parameters for map
bins_indiv = c(0, 400, 800, 1600, 3600, 7500, 10000, 15000, 20000)
rb_indiv <- brewer.pal(9, "Reds")
cv_pal_indiv <- colorBin(rb_indiv, bins = bins_indiv)

bins_all = c(0, 750, 1800, 4200, 9500, 14000, 20000, 27000, 100000)
rb_all <- brewer.pal(9, "Reds")
cv_pal_all <- colorBin(rb_all, bins = bins_all)

# mapping
map = basemap %>% 
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_all$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_all(df_china_invest_grouped_all$amount),
              group='All',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_all$Country, 'All', df_china_invest_grouped_all$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%  
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_agri$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_agri$amount),
              group='Agriculture',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_agri$Country, 'All', df_china_invest_grouped_agri$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>% 
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_chem$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_chem$amount),
              group='Chemicals',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_chem$Country, 'All', df_china_invest_grouped_chem$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_energy$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_energy$amount),
              group='Energy',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_energy$Country, 'All', df_china_invest_grouped_energy$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_ent$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_ent$amount),
              group='Entertainment',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_ent$Country, 'All', df_china_invest_grouped_ent$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_fin$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_fin$amount),
              group='Finance',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_fin$Country, 'All', df_china_invest_grouped_fin$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_health$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_health$amount),
              group='Health',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_health$Country, 'All', df_china_invest_grouped_health$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_logs$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_logs$amount),
              group='Logistics',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_logs$Country, 'All', df_china_invest_grouped_logs$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_metals$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_metals$amount),
              group='Metals',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_metals$Country, 'All', df_china_invest_grouped_metals$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_other$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_other$amount),
              group='Other',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_other$Country, 'All', df_china_invest_grouped_other$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_real$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_real$amount),
              group='Real estate',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_real$Country, 'All', df_china_invest_grouped_real$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_tech$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_tech$amount),
              group='Technology',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_tech$Country, 'All', df_china_invest_grouped_tech$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_tour$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_tour$amount),
              group='Tourism',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_tour$Country, 'All', df_china_invest_grouped_tour$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_trans$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_trans$amount),
              group='Transport',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_trans$Country, 'All', df_china_invest_grouped_trans$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto")) %>%
  addPolygons(data=plot_map[plot_map$ADM0_A3 %in% df_china_invest_grouped_util$alpha3, ],
              stroke = FALSE,
              smoothFactor = 0.1,
              fillOpacity = 0.8,
              fillColor = ~cv_pal_indiv(df_china_invest_grouped_util$amount),
              group='Utilities',
              label = sprintf("<strong>%s</strong><br/><strong>Sector</strong>: %s<br/><strong>Investment ($m)</strong>: %1.f",
                              df_china_invest_grouped_util$Country, 'All', df_china_invest_grouped_util$amount) %>% lapply(htmltools::HTML),
              labelOptions = labelOptions(
                                 style = list("font-weight" = "normal", padding = "3px 8px"),
                                 textsize = "12px", direction = "auto"))

map
```

